// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePayment = "payments"

// Payment mapped from table <payments>
type Payment struct {
	PaymentID         int64     `gorm:"column:payment_id;primaryKey" json:"payment_id"`
	FromAccountID     int64     `gorm:"column:from_account_id;not null" json:"from_account_id"`
	ToAccountID       int64     `gorm:"column:to_account_id" json:"to_account_id"`
	PaymentType       string    `gorm:"column:payment_type;not null" json:"payment_type"`
	PaymentMethod     string    `gorm:"column:payment_method;not null" json:"payment_method"`
	Amount            float64   `gorm:"column:amount;not null" json:"amount"`
	Currency          string    `gorm:"column:currency;not null" json:"currency"`
	Status            string    `gorm:"column:status;not null" json:"status"`
	ReferenceNumber   string    `gorm:"column:reference_number;not null" json:"reference_number"`
	ExternalReference string    `gorm:"column:external_reference" json:"external_reference"`
	ScheduledAt       time.Time `gorm:"column:scheduled_at" json:"scheduled_at"`
	ProcessedAt       time.Time `gorm:"column:processed_at" json:"processed_at"`
	CreationTime      time.Time `gorm:"column:creation_time" json:"creation_time"`
	ModifiedTime      time.Time `gorm:"column:modified_time" json:"modified_time"`
}

// TableName Payment's table name
func (*Payment) TableName() string {
	return TableNamePayment
}
