// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"card-service/internal/client"
	"card-service/internal/conf"
	"card-service/internal/data"
	"card-service/internal/handler"
	"card-service/internal/server"
	"card-service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	cardRepo := data.NewCardRepo(dataData)
	accountServiceClient := client.NewAccountServiceClient()
	accountClient := client.NewAccountClient(accountServiceClient)
	cardUsecase := handler.NewCardUsecase(cardRepo, accountClient)
	cardServiceService := service.NewCardServiceService(cardUsecase)
	grpcServer := server.NewGRPCServer(confServer, cardServiceService, logger)
	httpServer := server.NewHTTPServer(confServer, cardServiceService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
