// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.2
// source: api/customer/customer.proto

package customer

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationCustomerServiceCreateCustomer = "/customer.CustomerService/CreateCustomer"
const OperationCustomerServiceDiscardCustomer = "/customer.CustomerService/DiscardCustomer"
const OperationCustomerServiceGetCustomer = "/customer.CustomerService/GetCustomer"
const OperationCustomerServiceUpdateCustomer = "/customer.CustomerService/UpdateCustomer"
const OperationCustomerServiceUpdateCustomerStatus = "/customer.CustomerService/UpdateCustomerStatus"
const OperationCustomerServiceUpdateKycStatus = "/customer.CustomerService/UpdateKycStatus"

type CustomerServiceHTTPServer interface {
	// CreateCustomercreate
	CreateCustomer(context.Context, *CreateCustomerRequest) (*CreateCustomerResponse, error)
	// DiscardCustomerdiscard
	DiscardCustomer(context.Context, *DiscardCustomerRequest) (*Customer, error)
	// GetCustomer get
	GetCustomer(context.Context, *GetCustomerRequest) (*GetCustomerResponse, error)
	// UpdateCustomerupdate
	UpdateCustomer(context.Context, *UpdateCustomerRequest) (*UpdateCustomerResponse, error)
	// UpdateCustomerStatusupdate
	UpdateCustomerStatus(context.Context, *UpdateCustomerStatusRequest) (*Customer, error)
	// UpdateKycStatusupdate kyc
	UpdateKycStatus(context.Context, *UpdateKycStatusRequest) (*Customer, error)
}

func RegisterCustomerServiceHTTPServer(s *http.Server, srv CustomerServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/customer/create", _CustomerService_CreateCustomer0_HTTP_Handler(srv))
	r.GET("/customer/{customer_id}", _CustomerService_GetCustomer0_HTTP_Handler(srv))
	r.PATCH("/customer/update/{customer_id}", _CustomerService_UpdateCustomer0_HTTP_Handler(srv))
	r.PATCH("/customer/{customer_id}/kyc", _CustomerService_UpdateKycStatus0_HTTP_Handler(srv))
	r.PATCH("/customer/{customer_id}/status", _CustomerService_UpdateCustomerStatus0_HTTP_Handler(srv))
	r.PATCH("/customer/{customer_id}/discard", _CustomerService_DiscardCustomer0_HTTP_Handler(srv))
}

func _CustomerService_CreateCustomer0_HTTP_Handler(srv CustomerServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateCustomerRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCustomerServiceCreateCustomer)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateCustomer(ctx, req.(*CreateCustomerRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateCustomerResponse)
		return ctx.Result(200, reply)
	}
}

func _CustomerService_GetCustomer0_HTTP_Handler(srv CustomerServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCustomerRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCustomerServiceGetCustomer)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCustomer(ctx, req.(*GetCustomerRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCustomerResponse)
		return ctx.Result(200, reply)
	}
}

func _CustomerService_UpdateCustomer0_HTTP_Handler(srv CustomerServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateCustomerRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCustomerServiceUpdateCustomer)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateCustomer(ctx, req.(*UpdateCustomerRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateCustomerResponse)
		return ctx.Result(200, reply)
	}
}

func _CustomerService_UpdateKycStatus0_HTTP_Handler(srv CustomerServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateKycStatusRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCustomerServiceUpdateKycStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateKycStatus(ctx, req.(*UpdateKycStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Customer)
		return ctx.Result(200, reply)
	}
}

func _CustomerService_UpdateCustomerStatus0_HTTP_Handler(srv CustomerServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateCustomerStatusRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCustomerServiceUpdateCustomerStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateCustomerStatus(ctx, req.(*UpdateCustomerStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Customer)
		return ctx.Result(200, reply)
	}
}

func _CustomerService_DiscardCustomer0_HTTP_Handler(srv CustomerServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DiscardCustomerRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCustomerServiceDiscardCustomer)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DiscardCustomer(ctx, req.(*DiscardCustomerRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Customer)
		return ctx.Result(200, reply)
	}
}

type CustomerServiceHTTPClient interface {
	// CreateCustomercreate
	CreateCustomer(ctx context.Context, req *CreateCustomerRequest, opts ...http.CallOption) (rsp *CreateCustomerResponse, err error)
	// DiscardCustomerdiscard
	DiscardCustomer(ctx context.Context, req *DiscardCustomerRequest, opts ...http.CallOption) (rsp *Customer, err error)
	// GetCustomer get
	GetCustomer(ctx context.Context, req *GetCustomerRequest, opts ...http.CallOption) (rsp *GetCustomerResponse, err error)
	// UpdateCustomerupdate
	UpdateCustomer(ctx context.Context, req *UpdateCustomerRequest, opts ...http.CallOption) (rsp *UpdateCustomerResponse, err error)
	// UpdateCustomerStatusupdate
	UpdateCustomerStatus(ctx context.Context, req *UpdateCustomerStatusRequest, opts ...http.CallOption) (rsp *Customer, err error)
	// UpdateKycStatusupdate kyc
	UpdateKycStatus(ctx context.Context, req *UpdateKycStatusRequest, opts ...http.CallOption) (rsp *Customer, err error)
}

type CustomerServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewCustomerServiceHTTPClient(client *http.Client) CustomerServiceHTTPClient {
	return &CustomerServiceHTTPClientImpl{client}
}

// CreateCustomercreate
func (c *CustomerServiceHTTPClientImpl) CreateCustomer(ctx context.Context, in *CreateCustomerRequest, opts ...http.CallOption) (*CreateCustomerResponse, error) {
	var out CreateCustomerResponse
	pattern := "/customer/create"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCustomerServiceCreateCustomer))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DiscardCustomerdiscard
func (c *CustomerServiceHTTPClientImpl) DiscardCustomer(ctx context.Context, in *DiscardCustomerRequest, opts ...http.CallOption) (*Customer, error) {
	var out Customer
	pattern := "/customer/{customer_id}/discard"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCustomerServiceDiscardCustomer))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetCustomer get
func (c *CustomerServiceHTTPClientImpl) GetCustomer(ctx context.Context, in *GetCustomerRequest, opts ...http.CallOption) (*GetCustomerResponse, error) {
	var out GetCustomerResponse
	pattern := "/customer/{customer_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCustomerServiceGetCustomer))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateCustomerupdate
func (c *CustomerServiceHTTPClientImpl) UpdateCustomer(ctx context.Context, in *UpdateCustomerRequest, opts ...http.CallOption) (*UpdateCustomerResponse, error) {
	var out UpdateCustomerResponse
	pattern := "/customer/update/{customer_id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCustomerServiceUpdateCustomer))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateCustomerStatusupdate
func (c *CustomerServiceHTTPClientImpl) UpdateCustomerStatus(ctx context.Context, in *UpdateCustomerStatusRequest, opts ...http.CallOption) (*Customer, error) {
	var out Customer
	pattern := "/customer/{customer_id}/status"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCustomerServiceUpdateCustomerStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateKycStatusupdate kyc
func (c *CustomerServiceHTTPClientImpl) UpdateKycStatus(ctx context.Context, in *UpdateKycStatusRequest, opts ...http.CallOption) (*Customer, error) {
	var out Customer
	pattern := "/customer/{customer_id}/kyc"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCustomerServiceUpdateKycStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
