// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCard = "cards"

// Card mapped from table <cards>
type Card struct {
	CardID         int64     `gorm:"column:card_id;primaryKey" json:"card_id"`
	AccountID      int64     `gorm:"column:account_id;not null" json:"account_id"`
	CardNumberHash string    `gorm:"column:card_number_hash;not null" json:"card_number_hash"`
	CardType       string    `gorm:"column:card_type;not null" json:"card_type"`
	CardStatus     string    `gorm:"column:card_status;not null" json:"card_status"`
	ExpiryDate     time.Time `gorm:"column:expiry_date;not null" json:"expiry_date"`
	DailyLimit     float64   `gorm:"column:daily_limit" json:"daily_limit"`
	MonthlyLimit   float64   `gorm:"column:monthly_limit" json:"monthly_limit"`
	CreationTime   time.Time `gorm:"column:creation_time" json:"creation_time"`
	ModifiedTime   time.Time `gorm:"column:modified_time" json:"modified_time"`
	CreatedBy      string    `gorm:"column:created_by" json:"created_by"`
	ModifiedBy     string    `gorm:"column:modified_by" json:"modified_by"`
}

// TableName Card's table name
func (*Card) TableName() string {
	return TableNameCard
}
