// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/card/card.proto

package card

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Card struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CardId    string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	AccountId string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// for hash
	CardType      string                 `protobuf:"bytes,3,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`
	CardStatus    string                 `protobuf:"bytes,4,opt,name=card_status,json=cardStatus,proto3" json:"card_status,omitempty"`
	ExpiryDate    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`
	DailyLimit    string                 `protobuf:"bytes,6,opt,name=daily_limit,json=dailyLimit,proto3" json:"daily_limit,omitempty"`
	MonthlyLimit  string                 `protobuf:"bytes,7,opt,name=monthly_limit,json=monthlyLimit,proto3" json:"monthly_limit,omitempty"`
	CreationTime  *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=creation_time,json=creationTime,proto3" json:"creation_time,omitempty"`
	ModifiedTime  *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=modified_time,json=modifiedTime,proto3" json:"modified_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_api_card_card_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_api_card_card_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_api_card_card_proto_rawDescGZIP(), []int{0}
}

func (x *Card) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *Card) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Card) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *Card) GetCardStatus() string {
	if x != nil {
		return x.CardStatus
	}
	return ""
}

func (x *Card) GetExpiryDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiryDate
	}
	return nil
}

func (x *Card) GetDailyLimit() string {
	if x != nil {
		return x.DailyLimit
	}
	return ""
}

func (x *Card) GetMonthlyLimit() string {
	if x != nil {
		return x.MonthlyLimit
	}
	return ""
}

func (x *Card) GetCreationTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationTime
	}
	return nil
}

func (x *Card) GetModifiedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ModifiedTime
	}
	return nil
}

type CreateCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	CardNumber    string                 `protobuf:"bytes,2,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`       // userinput, will be hashed
	CardType      string                 `protobuf:"bytes,3,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`             // debit | credit | prepaid
	DailyLimit    string                 `protobuf:"bytes,4,opt,name=daily_limit,json=dailyLimit,proto3" json:"daily_limit,omitempty"`       // optional
	MonthlyLimit  string                 `protobuf:"bytes,5,opt,name=monthly_limit,json=monthlyLimit,proto3" json:"monthly_limit,omitempty"` // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCardRequest) Reset() {
	*x = CreateCardRequest{}
	mi := &file_api_card_card_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCardRequest) ProtoMessage() {}

func (x *CreateCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_card_card_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCardRequest.ProtoReflect.Descriptor instead.
func (*CreateCardRequest) Descriptor() ([]byte, []int) {
	return file_api_card_card_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCardRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CreateCardRequest) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *CreateCardRequest) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *CreateCardRequest) GetDailyLimit() string {
	if x != nil {
		return x.DailyLimit
	}
	return ""
}

func (x *CreateCardRequest) GetMonthlyLimit() string {
	if x != nil {
		return x.MonthlyLimit
	}
	return ""
}

type CreateCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          *Card                  `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCardResponse) Reset() {
	*x = CreateCardResponse{}
	mi := &file_api_card_card_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCardResponse) ProtoMessage() {}

func (x *CreateCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_card_card_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCardResponse.ProtoReflect.Descriptor instead.
func (*CreateCardResponse) Descriptor() ([]byte, []int) {
	return file_api_card_card_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCardResponse) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

type GetCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardRequest) Reset() {
	*x = GetCardRequest{}
	mi := &file_api_card_card_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardRequest) ProtoMessage() {}

func (x *GetCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_card_card_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardRequest.ProtoReflect.Descriptor instead.
func (*GetCardRequest) Descriptor() ([]byte, []int) {
	return file_api_card_card_proto_rawDescGZIP(), []int{3}
}

func (x *GetCardRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

type ListCardsByAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCardsByAccountRequest) Reset() {
	*x = ListCardsByAccountRequest{}
	mi := &file_api_card_card_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCardsByAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCardsByAccountRequest) ProtoMessage() {}

func (x *ListCardsByAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_card_card_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCardsByAccountRequest.ProtoReflect.Descriptor instead.
func (*ListCardsByAccountRequest) Descriptor() ([]byte, []int) {
	return file_api_card_card_proto_rawDescGZIP(), []int{4}
}

func (x *ListCardsByAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type ListCardsByAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*Card                `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCardsByAccountResponse) Reset() {
	*x = ListCardsByAccountResponse{}
	mi := &file_api_card_card_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCardsByAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCardsByAccountResponse) ProtoMessage() {}

func (x *ListCardsByAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_card_card_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCardsByAccountResponse.ProtoReflect.Descriptor instead.
func (*ListCardsByAccountResponse) Descriptor() ([]byte, []int) {
	return file_api_card_card_proto_rawDescGZIP(), []int{5}
}

func (x *ListCardsByAccountResponse) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

type UpdateCardStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	CardStatus    string                 `protobuf:"bytes,2,opt,name=card_status,json=cardStatus,proto3" json:"card_status,omitempty"` // active | blocked | expired
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCardStatusRequest) Reset() {
	*x = UpdateCardStatusRequest{}
	mi := &file_api_card_card_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCardStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCardStatusRequest) ProtoMessage() {}

func (x *UpdateCardStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_card_card_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCardStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateCardStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_card_card_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateCardStatusRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *UpdateCardStatusRequest) GetCardStatus() string {
	if x != nil {
		return x.CardStatus
	}
	return ""
}

type UpdateCardLimitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	DailyLimit    string                 `protobuf:"bytes,2,opt,name=daily_limit,json=dailyLimit,proto3" json:"daily_limit,omitempty"`
	MonthlyLimit  string                 `protobuf:"bytes,3,opt,name=monthly_limit,json=monthlyLimit,proto3" json:"monthly_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCardLimitRequest) Reset() {
	*x = UpdateCardLimitRequest{}
	mi := &file_api_card_card_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCardLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCardLimitRequest) ProtoMessage() {}

func (x *UpdateCardLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_card_card_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCardLimitRequest.ProtoReflect.Descriptor instead.
func (*UpdateCardLimitRequest) Descriptor() ([]byte, []int) {
	return file_api_card_card_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateCardLimitRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *UpdateCardLimitRequest) GetDailyLimit() string {
	if x != nil {
		return x.DailyLimit
	}
	return ""
}

func (x *UpdateCardLimitRequest) GetMonthlyLimit() string {
	if x != nil {
		return x.MonthlyLimit
	}
	return ""
}

var File_api_card_card_proto protoreflect.FileDescriptor

const file_api_card_card_proto_rawDesc = "" +
	"\n" +
	"\x13api/card/card.proto\x12\bapi.card\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x81\x03\n" +
	"\x04Card\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x1b\n" +
	"\tcard_type\x18\x03 \x01(\tR\bcardType\x12\x1f\n" +
	"\vcard_status\x18\x04 \x01(\tR\n" +
	"cardStatus\x12;\n" +
	"\vexpiry_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expiryDate\x12\x1f\n" +
	"\vdaily_limit\x18\x06 \x01(\tR\n" +
	"dailyLimit\x12#\n" +
	"\rmonthly_limit\x18\a \x01(\tR\fmonthlyLimit\x12?\n" +
	"\rcreation_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\fcreationTime\x12?\n" +
	"\rmodified_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\fmodifiedTime\"\xb6\x01\n" +
	"\x11CreateCardRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1f\n" +
	"\vcard_number\x18\x02 \x01(\tR\n" +
	"cardNumber\x12\x1b\n" +
	"\tcard_type\x18\x03 \x01(\tR\bcardType\x12\x1f\n" +
	"\vdaily_limit\x18\x04 \x01(\tR\n" +
	"dailyLimit\x12#\n" +
	"\rmonthly_limit\x18\x05 \x01(\tR\fmonthlyLimit\"8\n" +
	"\x12CreateCardResponse\x12\"\n" +
	"\x04card\x18\x01 \x01(\v2\x0e.api.card.CardR\x04card\")\n" +
	"\x0eGetCardRequest\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\":\n" +
	"\x19ListCardsByAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"B\n" +
	"\x1aListCardsByAccountResponse\x12$\n" +
	"\x05cards\x18\x01 \x03(\v2\x0e.api.card.CardR\x05cards\"S\n" +
	"\x17UpdateCardStatusRequest\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\x12\x1f\n" +
	"\vcard_status\x18\x02 \x01(\tR\n" +
	"cardStatus\"w\n" +
	"\x16UpdateCardLimitRequest\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\x12\x1f\n" +
	"\vdaily_limit\x18\x02 \x01(\tR\n" +
	"dailyLimit\x12#\n" +
	"\rmonthly_limit\x18\x03 \x01(\tR\fmonthlyLimit2\x94\x04\n" +
	"\vCardService\x12`\n" +
	"\n" +
	"CreateCard\x12\x1b.api.card.CreateCardRequest\x1a\x1c.api.card.CreateCardResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/card/create\x12L\n" +
	"\aGetCard\x12\x18.api.card.GetCardRequest\x1a\x0e.api.card.Card\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/card/{card_id}\x12\x83\x01\n" +
	"\x12ListCardsByAccount\x12#.api.card.ListCardsByAccountRequest\x1a$.api.card.ListCardsByAccountResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/account/{account_id}/card\x12h\n" +
	"\x10UpdateCardStatus\x12!.api.card.UpdateCardStatusRequest\x1a\x0e.api.card.Card\"!\x82\xd3\xe4\x93\x02\x1b:\x01*2\x16/card/{card_id}/status\x12e\n" +
	"\x0fUpdateCardLimit\x12 .api.card.UpdateCardLimitRequest\x1a\x0e.api.card.Card\" \x82\xd3\xe4\x93\x02\x1a:\x01*2\x15/card/{card_id}/limitB\x1cZ\x1acard-service/api/card;cardb\x06proto3"

var (
	file_api_card_card_proto_rawDescOnce sync.Once
	file_api_card_card_proto_rawDescData []byte
)

func file_api_card_card_proto_rawDescGZIP() []byte {
	file_api_card_card_proto_rawDescOnce.Do(func() {
		file_api_card_card_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_card_card_proto_rawDesc), len(file_api_card_card_proto_rawDesc)))
	})
	return file_api_card_card_proto_rawDescData
}

var file_api_card_card_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_card_card_proto_goTypes = []any{
	(*Card)(nil),                       // 0: api.card.Card
	(*CreateCardRequest)(nil),          // 1: api.card.CreateCardRequest
	(*CreateCardResponse)(nil),         // 2: api.card.CreateCardResponse
	(*GetCardRequest)(nil),             // 3: api.card.GetCardRequest
	(*ListCardsByAccountRequest)(nil),  // 4: api.card.ListCardsByAccountRequest
	(*ListCardsByAccountResponse)(nil), // 5: api.card.ListCardsByAccountResponse
	(*UpdateCardStatusRequest)(nil),    // 6: api.card.UpdateCardStatusRequest
	(*UpdateCardLimitRequest)(nil),     // 7: api.card.UpdateCardLimitRequest
	(*timestamppb.Timestamp)(nil),      // 8: google.protobuf.Timestamp
}
var file_api_card_card_proto_depIdxs = []int32{
	8,  // 0: api.card.Card.expiry_date:type_name -> google.protobuf.Timestamp
	8,  // 1: api.card.Card.creation_time:type_name -> google.protobuf.Timestamp
	8,  // 2: api.card.Card.modified_time:type_name -> google.protobuf.Timestamp
	0,  // 3: api.card.CreateCardResponse.card:type_name -> api.card.Card
	0,  // 4: api.card.ListCardsByAccountResponse.cards:type_name -> api.card.Card
	1,  // 5: api.card.CardService.CreateCard:input_type -> api.card.CreateCardRequest
	3,  // 6: api.card.CardService.GetCard:input_type -> api.card.GetCardRequest
	4,  // 7: api.card.CardService.ListCardsByAccount:input_type -> api.card.ListCardsByAccountRequest
	6,  // 8: api.card.CardService.UpdateCardStatus:input_type -> api.card.UpdateCardStatusRequest
	7,  // 9: api.card.CardService.UpdateCardLimit:input_type -> api.card.UpdateCardLimitRequest
	2,  // 10: api.card.CardService.CreateCard:output_type -> api.card.CreateCardResponse
	0,  // 11: api.card.CardService.GetCard:output_type -> api.card.Card
	5,  // 12: api.card.CardService.ListCardsByAccount:output_type -> api.card.ListCardsByAccountResponse
	0,  // 13: api.card.CardService.UpdateCardStatus:output_type -> api.card.Card
	0,  // 14: api.card.CardService.UpdateCardLimit:output_type -> api.card.Card
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_card_card_proto_init() }
func file_api_card_card_proto_init() {
	if File_api_card_card_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_card_card_proto_rawDesc), len(file_api_card_card_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_card_card_proto_goTypes,
		DependencyIndexes: file_api_card_card_proto_depIdxs,
		MessageInfos:      file_api_card_card_proto_msgTypes,
	}.Build()
	File_api_card_card_proto = out.File
	file_api_card_card_proto_goTypes = nil
	file_api_card_card_proto_depIdxs = nil
}
