// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.2
// source: api/card/card.proto

package card

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationCardServiceCreateCard = "/api.card.CardService/CreateCard"
const OperationCardServiceGetCard = "/api.card.CardService/GetCard"
const OperationCardServiceListCardsByAccount = "/api.card.CardService/ListCardsByAccount"
const OperationCardServiceUpdateCardLimit = "/api.card.CardService/UpdateCardLimit"
const OperationCardServiceUpdateCardStatus = "/api.card.CardService/UpdateCardStatus"

type CardServiceHTTPServer interface {
	CreateCard(context.Context, *CreateCardRequest) (*CreateCardResponse, error)
	GetCard(context.Context, *GetCardRequest) (*Card, error)
	ListCardsByAccount(context.Context, *ListCardsByAccountRequest) (*ListCardsByAccountResponse, error)
	UpdateCardLimit(context.Context, *UpdateCardLimitRequest) (*Card, error)
	UpdateCardStatus(context.Context, *UpdateCardStatusRequest) (*Card, error)
}

func RegisterCardServiceHTTPServer(s *http.Server, srv CardServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/card/create", _CardService_CreateCard0_HTTP_Handler(srv))
	r.GET("/card/{card_id}", _CardService_GetCard0_HTTP_Handler(srv))
	r.GET("/account/{account_id}/card", _CardService_ListCardsByAccount0_HTTP_Handler(srv))
	r.PATCH("/card/{card_id}/status", _CardService_UpdateCardStatus0_HTTP_Handler(srv))
	r.PATCH("/card/{card_id}/limit", _CardService_UpdateCardLimit0_HTTP_Handler(srv))
}

func _CardService_CreateCard0_HTTP_Handler(srv CardServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateCardRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCardServiceCreateCard)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateCard(ctx, req.(*CreateCardRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateCardResponse)
		return ctx.Result(200, reply)
	}
}

func _CardService_GetCard0_HTTP_Handler(srv CardServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCardRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCardServiceGetCard)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCard(ctx, req.(*GetCardRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Card)
		return ctx.Result(200, reply)
	}
}

func _CardService_ListCardsByAccount0_HTTP_Handler(srv CardServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListCardsByAccountRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCardServiceListCardsByAccount)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListCardsByAccount(ctx, req.(*ListCardsByAccountRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListCardsByAccountResponse)
		return ctx.Result(200, reply)
	}
}

func _CardService_UpdateCardStatus0_HTTP_Handler(srv CardServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateCardStatusRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCardServiceUpdateCardStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateCardStatus(ctx, req.(*UpdateCardStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Card)
		return ctx.Result(200, reply)
	}
}

func _CardService_UpdateCardLimit0_HTTP_Handler(srv CardServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateCardLimitRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCardServiceUpdateCardLimit)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateCardLimit(ctx, req.(*UpdateCardLimitRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Card)
		return ctx.Result(200, reply)
	}
}

type CardServiceHTTPClient interface {
	CreateCard(ctx context.Context, req *CreateCardRequest, opts ...http.CallOption) (rsp *CreateCardResponse, err error)
	GetCard(ctx context.Context, req *GetCardRequest, opts ...http.CallOption) (rsp *Card, err error)
	ListCardsByAccount(ctx context.Context, req *ListCardsByAccountRequest, opts ...http.CallOption) (rsp *ListCardsByAccountResponse, err error)
	UpdateCardLimit(ctx context.Context, req *UpdateCardLimitRequest, opts ...http.CallOption) (rsp *Card, err error)
	UpdateCardStatus(ctx context.Context, req *UpdateCardStatusRequest, opts ...http.CallOption) (rsp *Card, err error)
}

type CardServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewCardServiceHTTPClient(client *http.Client) CardServiceHTTPClient {
	return &CardServiceHTTPClientImpl{client}
}

func (c *CardServiceHTTPClientImpl) CreateCard(ctx context.Context, in *CreateCardRequest, opts ...http.CallOption) (*CreateCardResponse, error) {
	var out CreateCardResponse
	pattern := "/card/create"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCardServiceCreateCard))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CardServiceHTTPClientImpl) GetCard(ctx context.Context, in *GetCardRequest, opts ...http.CallOption) (*Card, error) {
	var out Card
	pattern := "/card/{card_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCardServiceGetCard))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CardServiceHTTPClientImpl) ListCardsByAccount(ctx context.Context, in *ListCardsByAccountRequest, opts ...http.CallOption) (*ListCardsByAccountResponse, error) {
	var out ListCardsByAccountResponse
	pattern := "/account/{account_id}/card"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCardServiceListCardsByAccount))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CardServiceHTTPClientImpl) UpdateCardLimit(ctx context.Context, in *UpdateCardLimitRequest, opts ...http.CallOption) (*Card, error) {
	var out Card
	pattern := "/card/{card_id}/limit"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCardServiceUpdateCardLimit))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CardServiceHTTPClientImpl) UpdateCardStatus(ctx context.Context, in *UpdateCardStatusRequest, opts ...http.CallOption) (*Card, error) {
	var out Card
	pattern := "/card/{card_id}/status"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCardServiceUpdateCardStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
