// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAccount = "accounts"

// Account mapped from table <accounts>
type Account struct {
	AccountID         int64     `gorm:"column:account_id;primaryKey" json:"account_id"`
	CustomerID        int64     `gorm:"column:customer_id;not null" json:"customer_id"`
	AccountNumber     string    `gorm:"column:account_number;not null" json:"account_number"`
	AccountType       string    `gorm:"column:account_type;not null" json:"account_type"`
	Currency          string    `gorm:"column:currency;not null" json:"currency"`
	Status            string    `gorm:"column:status;not null" json:"status"`
	AvailableBalance  float64   `gorm:"column:available_balance;not null" json:"available_balance"`
	PendingBalance    float64   `gorm:"column:pending_balance;not null" json:"pending_balance"`
	CreditLimit       float64   `gorm:"column:credit_limit" json:"credit_limit"`
	LastTransactionAt time.Time `gorm:"column:last_transaction_at" json:"last_transaction_at"`
	CreationTime      time.Time `gorm:"column:creation_time" json:"creation_time"`
	ModifiedTime      time.Time `gorm:"column:modified_time" json:"modified_time"`
	CreatedBy         string    `gorm:"column:created_by" json:"created_by"`
	ModifiedBy        string    `gorm:"column:modified_by" json:"modified_by"`
}

// TableName Account's table name
func (*Account) TableName() string {
	return TableNameAccount
}
