// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/account/account.proto

package account

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Account struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccountId        string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	CustomerId       string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	AccountNumber    string                 `protobuf:"bytes,3,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	AccountType      string                 `protobuf:"bytes,4,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	Currency         string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Status           string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	AvailableBalance string                 `protobuf:"bytes,7,opt,name=available_balance,json=availableBalance,proto3" json:"available_balance,omitempty"`
	PendingBalance   string                 `protobuf:"bytes,8,opt,name=pending_balance,json=pendingBalance,proto3" json:"pending_balance,omitempty"`
	CreditLimit      string                 `protobuf:"bytes,9,opt,name=credit_limit,json=creditLimit,proto3" json:"credit_limit,omitempty"`
	CreationTime     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=creation_time,json=creationTime,proto3" json:"creation_time,omitempty"`
	ModifiedTime     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=modified_time,json=modifiedTime,proto3" json:"modified_time,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_api_account_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_api_account_account_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Account) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Account) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *Account) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *Account) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Account) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Account) GetAvailableBalance() string {
	if x != nil {
		return x.AvailableBalance
	}
	return ""
}

func (x *Account) GetPendingBalance() string {
	if x != nil {
		return x.PendingBalance
	}
	return ""
}

func (x *Account) GetCreditLimit() string {
	if x != nil {
		return x.CreditLimit
	}
	return ""
}

func (x *Account) GetCreationTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationTime
	}
	return nil
}

func (x *Account) GetModifiedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ModifiedTime
	}
	return nil
}

type CreateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	AccountNumber string                 `protobuf:"bytes,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"` //user inp
	AccountType   string                 `protobuf:"bytes,3,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`       // checking | savings | credit | wallet
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`                                // ISO code
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_api_account_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_api_account_account_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAccountRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CreateAccountRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *CreateAccountRequest) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *CreateAccountRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type CreateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	mi := &file_api_account_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_api_account_account_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_api_account_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_api_account_account_proto_rawDescGZIP(), []int{3}
}

func (x *GetAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type ListAccountsByCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountsByCustomerRequest) Reset() {
	*x = ListAccountsByCustomerRequest{}
	mi := &file_api_account_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsByCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsByCustomerRequest) ProtoMessage() {}

func (x *ListAccountsByCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsByCustomerRequest.ProtoReflect.Descriptor instead.
func (*ListAccountsByCustomerRequest) Descriptor() ([]byte, []int) {
	return file_api_account_account_proto_rawDescGZIP(), []int{4}
}

func (x *ListAccountsByCustomerRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type ListAccountsByCustomerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*Account             `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountsByCustomerResponse) Reset() {
	*x = ListAccountsByCustomerResponse{}
	mi := &file_api_account_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsByCustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsByCustomerResponse) ProtoMessage() {}

func (x *ListAccountsByCustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsByCustomerResponse.ProtoReflect.Descriptor instead.
func (*ListAccountsByCustomerResponse) Descriptor() ([]byte, []int) {
	return file_api_account_account_proto_rawDescGZIP(), []int{5}
}

func (x *ListAccountsByCustomerResponse) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

type UpdateAccountStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // active,frozen,closed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountStatusRequest) Reset() {
	*x = UpdateAccountStatusRequest{}
	mi := &file_api_account_account_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountStatusRequest) ProtoMessage() {}

func (x *UpdateAccountStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_account_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateAccountStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_account_account_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateAccountStatusRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *UpdateAccountStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_api_account_account_proto protoreflect.FileDescriptor

const file_api_account_account_proto_rawDesc = "" +
	"\n" +
	"\x19api/account/account.proto\x12\vapi.account\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc2\x03\n" +
	"\aAccount\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12%\n" +
	"\x0eaccount_number\x18\x03 \x01(\tR\raccountNumber\x12!\n" +
	"\faccount_type\x18\x04 \x01(\tR\vaccountType\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12+\n" +
	"\x11available_balance\x18\a \x01(\tR\x10availableBalance\x12'\n" +
	"\x0fpending_balance\x18\b \x01(\tR\x0ependingBalance\x12!\n" +
	"\fcredit_limit\x18\t \x01(\tR\vcreditLimit\x12?\n" +
	"\rcreation_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\fcreationTime\x12?\n" +
	"\rmodified_time\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\fmodifiedTime\"\x9d\x01\n" +
	"\x14CreateAccountRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\tR\raccountNumber\x12!\n" +
	"\faccount_type\x18\x03 \x01(\tR\vaccountType\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\"G\n" +
	"\x15CreateAccountResponse\x12.\n" +
	"\aaccount\x18\x01 \x01(\v2\x14.api.account.AccountR\aaccount\"2\n" +
	"\x11GetAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"@\n" +
	"\x1dListAccountsByCustomerRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\"R\n" +
	"\x1eListAccountsByCustomerResponse\x120\n" +
	"\baccounts\x18\x01 \x03(\v2\x14.api.account.AccountR\baccounts\"S\n" +
	"\x1aUpdateAccountStatusRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\x83\x04\n" +
	"\x0eAccountService\x12r\n" +
	"\rCreateAccount\x12!.api.account.CreateAccountRequest\x1a\".api.account.CreateAccountResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/account/create\x12a\n" +
	"\n" +
	"GetAccount\x12\x1e.api.account.GetAccountRequest\x1a\x14.api.account.Account\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/account/{account_id}\x12\x9a\x01\n" +
	"\x16ListAccountsByCustomer\x12*.api.account.ListAccountsByCustomerRequest\x1a+.api.account.ListAccountsByCustomerResponse\"'\x82\xd3\xe4\x93\x02!\x12\x1f/customer/{customer_id}/account\x12}\n" +
	"\x13UpdateAccountStatus\x12'.api.account.UpdateAccountStatusRequest\x1a\x14.api.account.Account\"'\x82\xd3\xe4\x93\x02!:\x01*2\x1c/account/{account_id}/statusB4\n" +
	"\vapi.accountP\x01Z#account-service/api/account;accountb\x06proto3"

var (
	file_api_account_account_proto_rawDescOnce sync.Once
	file_api_account_account_proto_rawDescData []byte
)

func file_api_account_account_proto_rawDescGZIP() []byte {
	file_api_account_account_proto_rawDescOnce.Do(func() {
		file_api_account_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_account_account_proto_rawDesc), len(file_api_account_account_proto_rawDesc)))
	})
	return file_api_account_account_proto_rawDescData
}

var file_api_account_account_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_account_account_proto_goTypes = []any{
	(*Account)(nil),                        // 0: api.account.Account
	(*CreateAccountRequest)(nil),           // 1: api.account.CreateAccountRequest
	(*CreateAccountResponse)(nil),          // 2: api.account.CreateAccountResponse
	(*GetAccountRequest)(nil),              // 3: api.account.GetAccountRequest
	(*ListAccountsByCustomerRequest)(nil),  // 4: api.account.ListAccountsByCustomerRequest
	(*ListAccountsByCustomerResponse)(nil), // 5: api.account.ListAccountsByCustomerResponse
	(*UpdateAccountStatusRequest)(nil),     // 6: api.account.UpdateAccountStatusRequest
	(*timestamppb.Timestamp)(nil),          // 7: google.protobuf.Timestamp
}
var file_api_account_account_proto_depIdxs = []int32{
	7, // 0: api.account.Account.creation_time:type_name -> google.protobuf.Timestamp
	7, // 1: api.account.Account.modified_time:type_name -> google.protobuf.Timestamp
	0, // 2: api.account.CreateAccountResponse.account:type_name -> api.account.Account
	0, // 3: api.account.ListAccountsByCustomerResponse.accounts:type_name -> api.account.Account
	1, // 4: api.account.AccountService.CreateAccount:input_type -> api.account.CreateAccountRequest
	3, // 5: api.account.AccountService.GetAccount:input_type -> api.account.GetAccountRequest
	4, // 6: api.account.AccountService.ListAccountsByCustomer:input_type -> api.account.ListAccountsByCustomerRequest
	6, // 7: api.account.AccountService.UpdateAccountStatus:input_type -> api.account.UpdateAccountStatusRequest
	2, // 8: api.account.AccountService.CreateAccount:output_type -> api.account.CreateAccountResponse
	0, // 9: api.account.AccountService.GetAccount:output_type -> api.account.Account
	5, // 10: api.account.AccountService.ListAccountsByCustomer:output_type -> api.account.ListAccountsByCustomerResponse
	0, // 11: api.account.AccountService.UpdateAccountStatus:output_type -> api.account.Account
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_account_account_proto_init() }
func file_api_account_account_proto_init() {
	if File_api_account_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_account_account_proto_rawDesc), len(file_api_account_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_account_account_proto_goTypes,
		DependencyIndexes: file_api_account_account_proto_depIdxs,
		MessageInfos:      file_api_account_account_proto_msgTypes,
	}.Build()
	File_api_account_account_proto = out.File
	file_api_account_account_proto_goTypes = nil
	file_api_account_account_proto_depIdxs = nil
}
