// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.2
// source: api/account/account.proto

package account

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationAccountServiceCreateAccount = "/api.account.AccountService/CreateAccount"
const OperationAccountServiceGetAccount = "/api.account.AccountService/GetAccount"
const OperationAccountServiceListAccountsByCustomer = "/api.account.AccountService/ListAccountsByCustomer"
const OperationAccountServiceUpdateAccountStatus = "/api.account.AccountService/UpdateAccountStatus"

type AccountServiceHTTPServer interface {
	CreateAccount(context.Context, *CreateAccountRequest) (*CreateAccountResponse, error)
	GetAccount(context.Context, *GetAccountRequest) (*Account, error)
	ListAccountsByCustomer(context.Context, *ListAccountsByCustomerRequest) (*ListAccountsByCustomerResponse, error)
	UpdateAccountStatus(context.Context, *UpdateAccountStatusRequest) (*Account, error)
}

func RegisterAccountServiceHTTPServer(s *http.Server, srv AccountServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/account/create", _AccountService_CreateAccount0_HTTP_Handler(srv))
	r.GET("/account/{account_id}", _AccountService_GetAccount0_HTTP_Handler(srv))
	r.GET("/customer/{customer_id}/account", _AccountService_ListAccountsByCustomer0_HTTP_Handler(srv))
	r.PATCH("/account/{account_id}/status", _AccountService_UpdateAccountStatus0_HTTP_Handler(srv))
}

func _AccountService_CreateAccount0_HTTP_Handler(srv AccountServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateAccountRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAccountServiceCreateAccount)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateAccount(ctx, req.(*CreateAccountRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateAccountResponse)
		return ctx.Result(200, reply)
	}
}

func _AccountService_GetAccount0_HTTP_Handler(srv AccountServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAccountRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAccountServiceGetAccount)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAccount(ctx, req.(*GetAccountRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Account)
		return ctx.Result(200, reply)
	}
}

func _AccountService_ListAccountsByCustomer0_HTTP_Handler(srv AccountServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAccountsByCustomerRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAccountServiceListAccountsByCustomer)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAccountsByCustomer(ctx, req.(*ListAccountsByCustomerRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListAccountsByCustomerResponse)
		return ctx.Result(200, reply)
	}
}

func _AccountService_UpdateAccountStatus0_HTTP_Handler(srv AccountServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateAccountStatusRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAccountServiceUpdateAccountStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateAccountStatus(ctx, req.(*UpdateAccountStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Account)
		return ctx.Result(200, reply)
	}
}

type AccountServiceHTTPClient interface {
	CreateAccount(ctx context.Context, req *CreateAccountRequest, opts ...http.CallOption) (rsp *CreateAccountResponse, err error)
	GetAccount(ctx context.Context, req *GetAccountRequest, opts ...http.CallOption) (rsp *Account, err error)
	ListAccountsByCustomer(ctx context.Context, req *ListAccountsByCustomerRequest, opts ...http.CallOption) (rsp *ListAccountsByCustomerResponse, err error)
	UpdateAccountStatus(ctx context.Context, req *UpdateAccountStatusRequest, opts ...http.CallOption) (rsp *Account, err error)
}

type AccountServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewAccountServiceHTTPClient(client *http.Client) AccountServiceHTTPClient {
	return &AccountServiceHTTPClientImpl{client}
}

func (c *AccountServiceHTTPClientImpl) CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...http.CallOption) (*CreateAccountResponse, error) {
	var out CreateAccountResponse
	pattern := "/account/create"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAccountServiceCreateAccount))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AccountServiceHTTPClientImpl) GetAccount(ctx context.Context, in *GetAccountRequest, opts ...http.CallOption) (*Account, error) {
	var out Account
	pattern := "/account/{account_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAccountServiceGetAccount))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AccountServiceHTTPClientImpl) ListAccountsByCustomer(ctx context.Context, in *ListAccountsByCustomerRequest, opts ...http.CallOption) (*ListAccountsByCustomerResponse, error) {
	var out ListAccountsByCustomerResponse
	pattern := "/customer/{customer_id}/account"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAccountServiceListAccountsByCustomer))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AccountServiceHTTPClientImpl) UpdateAccountStatus(ctx context.Context, in *UpdateAccountStatusRequest, opts ...http.CallOption) (*Account, error) {
	var out Account
	pattern := "/account/{account_id}/status"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAccountServiceUpdateAccountStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
