// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"payment-service/internal/client"
	"payment-service/internal/conf"
	"payment-service/internal/data"
	"payment-service/internal/handler"
	"payment-service/internal/server"
	"payment-service/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	db := data.NewDB(dataData)
	paymentRepo := data.NewPaymentRepo(db)
	clientConn, err := account.NewGRPCConn()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	client := account.NewClient(clientConn)
	paymentUsecase := handler.NewPaymentUsecase(paymentRepo, client)
	paymentServiceService := service.NewPaymentServiceService(paymentUsecase)
	grpcServer := server.NewGRPCServer(confServer, paymentServiceService, logger)
	httpServer := server.NewHTTPServer(confServer, paymentServiceService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
