// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"transaction-service/internal/client"
	"transaction-service/internal/conf"
	"transaction-service/internal/data"
	"transaction-service/internal/handler"
	"transaction-service/internal/server"
	"transaction-service/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	transactionRepo := data.NewTransactionRepo(dataData)
	accountServiceClient := client.NewAccountServiceClient()
	accountClient := client.NewAccountClient(accountServiceClient)
	transactionUsecase := handler.NewTransactionUsecase(transactionRepo, accountClient)
	transactionServiceService := service.NewTransactionServiceService(transactionUsecase)
	grpcServer := server.NewGRPCServer(confServer, transactionServiceService, logger)
	httpServer := server.NewHTTPServer(confServer, transactionServiceService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
