// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCustomer = "customers"

// Customer mapped from table <customers>
type Customer struct {
	CustomerID     int64     `gorm:"column:customer_id;primaryKey" json:"customer_id"`
	CustomerNumber string    `gorm:"column:customer_number;not null" json:"customer_number"`
	FirstName      string    `gorm:"column:first_name;not null" json:"first_name"`
	LastName       string    `gorm:"column:last_name;not null" json:"last_name"`
	Email          string    `gorm:"column:email;not null" json:"email"`
	Phone          string    `gorm:"column:phone" json:"phone"`
	DateOfBirth    string    `gorm:"column:date_of_birth;not null" json:"date_of_birth"`
	Status         string    `gorm:"column:status;not null;default:active" json:"status"`
	KycStatus      string    `gorm:"column:kyc_status;not null;default:pending" json:"kyc_status"`
	CreationTime   time.Time `gorm:"column:creation_time;not null;default:now()" json:"creation_time"`
	ModifiedTime   time.Time `gorm:"column:modified_time;not null;default:now()" json:"modified_time"`
	DiscardTime    time.Time `gorm:"column:discard_time" json:"discard_time"`
	CreatedBy      int64     `gorm:"column:created_by" json:"created_by"`
	UpdatedBy      int64     `gorm:"column:updated_by" json:"updated_by"`
	DiscardedBy    int64     `gorm:"column:discarded_by" json:"discarded_by"`
	Discarded      string    `gorm:"column:discarded;default:N" json:"discarded"`
}

// TableName Customer's table name
func (*Customer) TableName() string {
	return TableNameCustomer
}
