// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTransaction = "transactions"

// Transaction mapped from table <transactions>
type Transaction struct {
	TransactionID        int64     `gorm:"column:transaction_id;primaryKey" json:"transaction_id"`
	AccountID            int64     `gorm:"column:account_id;not null" json:"account_id"`
	RelatedTransactionID int64     `gorm:"column:related_transaction_id" json:"related_transaction_id"`
	TransactionType      string    `gorm:"column:transaction_type;not null" json:"transaction_type"`
	Amount               float64   `gorm:"column:amount;not null" json:"amount"`
	Currency             string    `gorm:"column:currency;not null" json:"currency"`
	Status               string    `gorm:"column:status;not null" json:"status"`
	Description          string    `gorm:"column:description" json:"description"`
	ReferenceNumber      string    `gorm:"column:reference_number;not null" json:"reference_number"`
	MerchantInfo         string    `gorm:"column:merchant_info" json:"merchant_info"`
	TransactionTime      time.Time `gorm:"column:transaction_time;not null" json:"transaction_time"`
	CreatedAt            time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	PostedAt             time.Time `gorm:"column:posted_at" json:"posted_at"`
	ArchivedAt           time.Time `gorm:"column:archived_at" json:"archived_at"`
}

// TableName Transaction's table name
func (*Transaction) TableName() string {
	return TableNameTransaction
}
