// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.2
// source: api/transaction/transaction.proto

package transaction

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationTransactionServiceCreateTransaction = "/api.transaction.TransactionService/CreateTransaction"
const OperationTransactionServiceGetTransaction = "/api.transaction.TransactionService/GetTransaction"
const OperationTransactionServiceListTransactionsByAccount = "/api.transaction.TransactionService/ListTransactionsByAccount"

type TransactionServiceHTTPServer interface {
	CreateTransaction(context.Context, *CreateTransactionRequest) (*CreateTransactionResponse, error)
	// GetTransaction Get transaction by ID
	GetTransaction(context.Context, *GetTransactionRequest) (*Transaction, error)
	ListTransactionsByAccount(context.Context, *ListTransactionsByAccountRequest) (*ListTransactionsByAccountResponse, error)
}

func RegisterTransactionServiceHTTPServer(s *http.Server, srv TransactionServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/transaction/create", _TransactionService_CreateTransaction0_HTTP_Handler(srv))
	r.GET("/transaction/{transaction_id}", _TransactionService_GetTransaction0_HTTP_Handler(srv))
	r.GET("/accounts/{account_id}/transactions", _TransactionService_ListTransactionsByAccount0_HTTP_Handler(srv))
}

func _TransactionService_CreateTransaction0_HTTP_Handler(srv TransactionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateTransactionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTransactionServiceCreateTransaction)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateTransaction(ctx, req.(*CreateTransactionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateTransactionResponse)
		return ctx.Result(200, reply)
	}
}

func _TransactionService_GetTransaction0_HTTP_Handler(srv TransactionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetTransactionRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTransactionServiceGetTransaction)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTransaction(ctx, req.(*GetTransactionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Transaction)
		return ctx.Result(200, reply)
	}
}

func _TransactionService_ListTransactionsByAccount0_HTTP_Handler(srv TransactionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListTransactionsByAccountRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTransactionServiceListTransactionsByAccount)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListTransactionsByAccount(ctx, req.(*ListTransactionsByAccountRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListTransactionsByAccountResponse)
		return ctx.Result(200, reply)
	}
}

type TransactionServiceHTTPClient interface {
	CreateTransaction(ctx context.Context, req *CreateTransactionRequest, opts ...http.CallOption) (rsp *CreateTransactionResponse, err error)
	// GetTransaction Get transaction by ID
	GetTransaction(ctx context.Context, req *GetTransactionRequest, opts ...http.CallOption) (rsp *Transaction, err error)
	ListTransactionsByAccount(ctx context.Context, req *ListTransactionsByAccountRequest, opts ...http.CallOption) (rsp *ListTransactionsByAccountResponse, err error)
}

type TransactionServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewTransactionServiceHTTPClient(client *http.Client) TransactionServiceHTTPClient {
	return &TransactionServiceHTTPClientImpl{client}
}

func (c *TransactionServiceHTTPClientImpl) CreateTransaction(ctx context.Context, in *CreateTransactionRequest, opts ...http.CallOption) (*CreateTransactionResponse, error) {
	var out CreateTransactionResponse
	pattern := "/transaction/create"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTransactionServiceCreateTransaction))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetTransaction Get transaction by ID
func (c *TransactionServiceHTTPClientImpl) GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...http.CallOption) (*Transaction, error) {
	var out Transaction
	pattern := "/transaction/{transaction_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTransactionServiceGetTransaction))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TransactionServiceHTTPClientImpl) ListTransactionsByAccount(ctx context.Context, in *ListTransactionsByAccountRequest, opts ...http.CallOption) (*ListTransactionsByAccountResponse, error) {
	var out ListTransactionsByAccountResponse
	pattern := "/accounts/{account_id}/transactions"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTransactionServiceListTransactionsByAccount))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
