// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/transaction/transaction.proto

package transaction

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Transaction struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionId   string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	AccountId       string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	TransactionType string                 `protobuf:"bytes,3,opt,name=transaction_type,json=transactionType,proto3" json:"transaction_type,omitempty"` // DEBIT,CREDIT,REVERSAL
	Amount          string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency        string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Status          string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"` // SUCCESS,FAILED
	ReferenceNumber string                 `protobuf:"bytes,7,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`
	// "{}"
	MerchantInfo    string                 `protobuf:"bytes,8,opt,name=merchant_info,json=merchantInfo,proto3" json:"merchant_info,omitempty"`
	Description     string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	TransactionTime *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=transaction_time,json=transactionTime,proto3" json:"transaction_time,omitempty"`
	PostedAt        *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=posted_at,json=postedAt,proto3" json:"posted_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_api_transaction_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_api_transaction_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_api_transaction_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Transaction) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Transaction) GetTransactionType() string {
	if x != nil {
		return x.TransactionType
	}
	return ""
}

func (x *Transaction) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Transaction) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Transaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Transaction) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *Transaction) GetMerchantInfo() string {
	if x != nil {
		return x.MerchantInfo
	}
	return ""
}

func (x *Transaction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Transaction) GetTransactionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.TransactionTime
	}
	return nil
}

func (x *Transaction) GetPostedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PostedAt
	}
	return nil
}

type CreateTransactionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccountId       string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	TransactionType string                 `protobuf:"bytes,2,opt,name=transaction_type,json=transactionType,proto3" json:"transaction_type,omitempty"` // debit, credit
	Amount          string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency        string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Description     string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateTransactionRequest) Reset() {
	*x = CreateTransactionRequest{}
	mi := &file_api_transaction_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionRequest) ProtoMessage() {}

func (x *CreateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_transaction_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionRequest.ProtoReflect.Descriptor instead.
func (*CreateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_api_transaction_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTransactionRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CreateTransactionRequest) GetTransactionType() string {
	if x != nil {
		return x.TransactionType
	}
	return ""
}

func (x *CreateTransactionRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *CreateTransactionRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateTransactionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransactionResponse) Reset() {
	*x = CreateTransactionResponse{}
	mi := &file_api_transaction_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionResponse) ProtoMessage() {}

func (x *CreateTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_transaction_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionResponse.ProtoReflect.Descriptor instead.
func (*CreateTransactionResponse) Descriptor() ([]byte, []int) {
	return file_api_transaction_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTransactionResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type GetTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionRequest) Reset() {
	*x = GetTransactionRequest{}
	mi := &file_api_transaction_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionRequest) ProtoMessage() {}

func (x *GetTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_transaction_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return file_api_transaction_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *GetTransactionRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type ListTransactionsByAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsByAccountRequest) Reset() {
	*x = ListTransactionsByAccountRequest{}
	mi := &file_api_transaction_transaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsByAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsByAccountRequest) ProtoMessage() {}

func (x *ListTransactionsByAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_transaction_transaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsByAccountRequest.ProtoReflect.Descriptor instead.
func (*ListTransactionsByAccountRequest) Descriptor() ([]byte, []int) {
	return file_api_transaction_transaction_proto_rawDescGZIP(), []int{4}
}

func (x *ListTransactionsByAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type ListTransactionsByAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsByAccountResponse) Reset() {
	*x = ListTransactionsByAccountResponse{}
	mi := &file_api_transaction_transaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsByAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsByAccountResponse) ProtoMessage() {}

func (x *ListTransactionsByAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_transaction_transaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsByAccountResponse.ProtoReflect.Descriptor instead.
func (*ListTransactionsByAccountResponse) Descriptor() ([]byte, []int) {
	return file_api_transaction_transaction_proto_rawDescGZIP(), []int{5}
}

func (x *ListTransactionsByAccountResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

var File_api_transaction_transaction_proto protoreflect.FileDescriptor

const file_api_transaction_transaction_proto_rawDesc = "" +
	"\n" +
	"!api/transaction/transaction.proto\x12\x0fapi.transaction\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbc\x03\n" +
	"\vTransaction\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12)\n" +
	"\x10transaction_type\x18\x03 \x01(\tR\x0ftransactionType\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12)\n" +
	"\x10reference_number\x18\a \x01(\tR\x0freferenceNumber\x12#\n" +
	"\rmerchant_info\x18\b \x01(\tR\fmerchantInfo\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12E\n" +
	"\x10transaction_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x0ftransactionTime\x127\n" +
	"\tposted_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\bpostedAt\"\xba\x01\n" +
	"\x18CreateTransactionRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12)\n" +
	"\x10transaction_type\x18\x02 \x01(\tR\x0ftransactionType\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"[\n" +
	"\x19CreateTransactionResponse\x12>\n" +
	"\vtransaction\x18\x01 \x01(\v2\x1c.api.transaction.TransactionR\vtransaction\">\n" +
	"\x15GetTransactionRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\"A\n" +
	" ListTransactionsByAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"e\n" +
	"!ListTransactionsByAccountResponse\x12@\n" +
	"\ftransactions\x18\x01 \x03(\v2\x1c.api.transaction.TransactionR\ftransactions2\xd2\x03\n" +
	"\x12TransactionService\x12\x8a\x01\n" +
	"\x11CreateTransaction\x12).api.transaction.CreateTransactionRequest\x1a*.api.transaction.CreateTransactionResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/transaction/create\x12}\n" +
	"\x0eGetTransaction\x12&.api.transaction.GetTransactionRequest\x1a\x1c.api.transaction.Transaction\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/transaction/{transaction_id}\x12\xaf\x01\n" +
	"\x19ListTransactionsByAccount\x121.api.transaction.ListTransactionsByAccountRequest\x1a2.api.transaction.ListTransactionsByAccountResponse\"+\x82\xd3\xe4\x93\x02%\x12#/accounts/{account_id}/transactionsB1Z/transaction-service/api/transaction;transactionb\x06proto3"

var (
	file_api_transaction_transaction_proto_rawDescOnce sync.Once
	file_api_transaction_transaction_proto_rawDescData []byte
)

func file_api_transaction_transaction_proto_rawDescGZIP() []byte {
	file_api_transaction_transaction_proto_rawDescOnce.Do(func() {
		file_api_transaction_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_transaction_transaction_proto_rawDesc), len(file_api_transaction_transaction_proto_rawDesc)))
	})
	return file_api_transaction_transaction_proto_rawDescData
}

var file_api_transaction_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_transaction_transaction_proto_goTypes = []any{
	(*Transaction)(nil),                       // 0: api.transaction.Transaction
	(*CreateTransactionRequest)(nil),          // 1: api.transaction.CreateTransactionRequest
	(*CreateTransactionResponse)(nil),         // 2: api.transaction.CreateTransactionResponse
	(*GetTransactionRequest)(nil),             // 3: api.transaction.GetTransactionRequest
	(*ListTransactionsByAccountRequest)(nil),  // 4: api.transaction.ListTransactionsByAccountRequest
	(*ListTransactionsByAccountResponse)(nil), // 5: api.transaction.ListTransactionsByAccountResponse
	(*timestamppb.Timestamp)(nil),             // 6: google.protobuf.Timestamp
}
var file_api_transaction_transaction_proto_depIdxs = []int32{
	6, // 0: api.transaction.Transaction.transaction_time:type_name -> google.protobuf.Timestamp
	6, // 1: api.transaction.Transaction.posted_at:type_name -> google.protobuf.Timestamp
	0, // 2: api.transaction.CreateTransactionResponse.transaction:type_name -> api.transaction.Transaction
	0, // 3: api.transaction.ListTransactionsByAccountResponse.transactions:type_name -> api.transaction.Transaction
	1, // 4: api.transaction.TransactionService.CreateTransaction:input_type -> api.transaction.CreateTransactionRequest
	3, // 5: api.transaction.TransactionService.GetTransaction:input_type -> api.transaction.GetTransactionRequest
	4, // 6: api.transaction.TransactionService.ListTransactionsByAccount:input_type -> api.transaction.ListTransactionsByAccountRequest
	2, // 7: api.transaction.TransactionService.CreateTransaction:output_type -> api.transaction.CreateTransactionResponse
	0, // 8: api.transaction.TransactionService.GetTransaction:output_type -> api.transaction.Transaction
	5, // 9: api.transaction.TransactionService.ListTransactionsByAccount:output_type -> api.transaction.ListTransactionsByAccountResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_transaction_transaction_proto_init() }
func file_api_transaction_transaction_proto_init() {
	if File_api_transaction_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_transaction_transaction_proto_rawDesc), len(file_api_transaction_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_transaction_transaction_proto_goTypes,
		DependencyIndexes: file_api_transaction_transaction_proto_depIdxs,
		MessageInfos:      file_api_transaction_transaction_proto_msgTypes,
	}.Build()
	File_api_transaction_transaction_proto = out.File
	file_api_transaction_transaction_proto_goTypes = nil
	file_api_transaction_transaction_proto_depIdxs = nil
}
