// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/payment/payment.proto

package payment

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Payment struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PaymentId         string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	FromAccountId     string                 `protobuf:"bytes,2,opt,name=from_account_id,json=fromAccountId,proto3" json:"from_account_id,omitempty"`
	ToAccountId       string                 `protobuf:"bytes,3,opt,name=to_account_id,json=toAccountId,proto3" json:"to_account_id,omitempty"`
	PaymentType       string                 `protobuf:"bytes,4,opt,name=payment_type,json=paymentType,proto3" json:"payment_type,omitempty"`       // transfer, payment, topup
	PaymentMethod     string                 `protobuf:"bytes,5,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"` // card, bank_transfer, wallet
	Amount            string                 `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency          string                 `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`
	Status            string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"` // initiated, processing, completed, failed, reversed
	ReferenceNumber   string                 `protobuf:"bytes,9,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`
	ExternalReference string                 `protobuf:"bytes,10,opt,name=external_reference,json=externalReference,proto3" json:"external_reference,omitempty"`
	ScheduledAt       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	ProcessedAt       *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`
	CreationTime      *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=creation_time,json=creationTime,proto3" json:"creation_time,omitempty"`
	ModifiedTime      *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=modified_time,json=modifiedTime,proto3" json:"modified_time,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_api_payment_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_api_payment_payment_proto_rawDescGZIP(), []int{0}
}

func (x *Payment) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *Payment) GetFromAccountId() string {
	if x != nil {
		return x.FromAccountId
	}
	return ""
}

func (x *Payment) GetToAccountId() string {
	if x != nil {
		return x.ToAccountId
	}
	return ""
}

func (x *Payment) GetPaymentType() string {
	if x != nil {
		return x.PaymentType
	}
	return ""
}

func (x *Payment) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *Payment) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Payment) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Payment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Payment) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *Payment) GetExternalReference() string {
	if x != nil {
		return x.ExternalReference
	}
	return ""
}

func (x *Payment) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledAt
	}
	return nil
}

func (x *Payment) GetProcessedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProcessedAt
	}
	return nil
}

func (x *Payment) GetCreationTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationTime
	}
	return nil
}

func (x *Payment) GetModifiedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ModifiedTime
	}
	return nil
}

type CreatePaymentRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FromAccountId     string                 `protobuf:"bytes,1,opt,name=from_account_id,json=fromAccountId,proto3" json:"from_account_id,omitempty"`
	ToAccountId       string                 `protobuf:"bytes,2,opt,name=to_account_id,json=toAccountId,proto3" json:"to_account_id,omitempty"`
	PaymentType       string                 `protobuf:"bytes,3,opt,name=payment_type,json=paymentType,proto3" json:"payment_type,omitempty"`
	PaymentMethod     string                 `protobuf:"bytes,4,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	Amount            string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency          string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	ReferenceNumber   string                 `protobuf:"bytes,7,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`
	ExternalReference string                 `protobuf:"bytes,8,opt,name=external_reference,json=externalReference,proto3" json:"external_reference,omitempty"`
	ScheduledAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_api_payment_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_api_payment_payment_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePaymentRequest) GetFromAccountId() string {
	if x != nil {
		return x.FromAccountId
	}
	return ""
}

func (x *CreatePaymentRequest) GetToAccountId() string {
	if x != nil {
		return x.ToAccountId
	}
	return ""
}

func (x *CreatePaymentRequest) GetPaymentType() string {
	if x != nil {
		return x.PaymentType
	}
	return ""
}

func (x *CreatePaymentRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *CreatePaymentRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *CreatePaymentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreatePaymentRequest) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *CreatePaymentRequest) GetExternalReference() string {
	if x != nil {
		return x.ExternalReference
	}
	return ""
}

func (x *CreatePaymentRequest) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledAt
	}
	return nil
}

type CreatePaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *Payment               `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentResponse) Reset() {
	*x = CreatePaymentResponse{}
	mi := &file_api_payment_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentResponse) ProtoMessage() {}

func (x *CreatePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentResponse) Descriptor() ([]byte, []int) {
	return file_api_payment_payment_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePaymentResponse) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

type GetPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentRequest) Reset() {
	*x = GetPaymentRequest{}
	mi := &file_api_payment_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentRequest) ProtoMessage() {}

func (x *GetPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentRequest) Descriptor() ([]byte, []int) {
	return file_api_payment_payment_proto_rawDescGZIP(), []int{3}
}

func (x *GetPaymentRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

type GetPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *Payment               `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentResponse) Reset() {
	*x = GetPaymentResponse{}
	mi := &file_api_payment_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentResponse) ProtoMessage() {}

func (x *GetPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentResponse) Descriptor() ([]byte, []int) {
	return file_api_payment_payment_proto_rawDescGZIP(), []int{4}
}

func (x *GetPaymentResponse) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

type ListPaymentsByAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentsByAccountRequest) Reset() {
	*x = ListPaymentsByAccountRequest{}
	mi := &file_api_payment_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentsByAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentsByAccountRequest) ProtoMessage() {}

func (x *ListPaymentsByAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentsByAccountRequest.ProtoReflect.Descriptor instead.
func (*ListPaymentsByAccountRequest) Descriptor() ([]byte, []int) {
	return file_api_payment_payment_proto_rawDescGZIP(), []int{5}
}

func (x *ListPaymentsByAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type ListPaymentsByAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payments      []*Payment             `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentsByAccountResponse) Reset() {
	*x = ListPaymentsByAccountResponse{}
	mi := &file_api_payment_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentsByAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentsByAccountResponse) ProtoMessage() {}

func (x *ListPaymentsByAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentsByAccountResponse.ProtoReflect.Descriptor instead.
func (*ListPaymentsByAccountResponse) Descriptor() ([]byte, []int) {
	return file_api_payment_payment_proto_rawDescGZIP(), []int{6}
}

func (x *ListPaymentsByAccountResponse) GetPayments() []*Payment {
	if x != nil {
		return x.Payments
	}
	return nil
}

type UpdatePaymentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // processing, completed, failed, reversed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePaymentStatusRequest) Reset() {
	*x = UpdatePaymentStatusRequest{}
	mi := &file_api_payment_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaymentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaymentStatusRequest) ProtoMessage() {}

func (x *UpdatePaymentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaymentStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdatePaymentStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_payment_payment_proto_rawDescGZIP(), []int{7}
}

func (x *UpdatePaymentStatusRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *UpdatePaymentStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_api_payment_payment_proto protoreflect.FileDescriptor

const file_api_payment_payment_proto_rawDesc = "" +
	"\n" +
	"\x19api/payment/payment.proto\x12\vapi.payment\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe4\x04\n" +
	"\aPayment\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12&\n" +
	"\x0ffrom_account_id\x18\x02 \x01(\tR\rfromAccountId\x12\"\n" +
	"\rto_account_id\x18\x03 \x01(\tR\vtoAccountId\x12!\n" +
	"\fpayment_type\x18\x04 \x01(\tR\vpaymentType\x12%\n" +
	"\x0epayment_method\x18\x05 \x01(\tR\rpaymentMethod\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\a \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12)\n" +
	"\x10reference_number\x18\t \x01(\tR\x0freferenceNumber\x12-\n" +
	"\x12external_reference\x18\n" +
	" \x01(\tR\x11externalReference\x12=\n" +
	"\fscheduled_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\x12=\n" +
	"\fprocessed_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\vprocessedAt\x12?\n" +
	"\rcreation_time\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\fcreationTime\x12?\n" +
	"\rmodified_time\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\fmodifiedTime\"\xf9\x02\n" +
	"\x14CreatePaymentRequest\x12&\n" +
	"\x0ffrom_account_id\x18\x01 \x01(\tR\rfromAccountId\x12\"\n" +
	"\rto_account_id\x18\x02 \x01(\tR\vtoAccountId\x12!\n" +
	"\fpayment_type\x18\x03 \x01(\tR\vpaymentType\x12%\n" +
	"\x0epayment_method\x18\x04 \x01(\tR\rpaymentMethod\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12)\n" +
	"\x10reference_number\x18\a \x01(\tR\x0freferenceNumber\x12-\n" +
	"\x12external_reference\x18\b \x01(\tR\x11externalReference\x12=\n" +
	"\fscheduled_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\"G\n" +
	"\x15CreatePaymentResponse\x12.\n" +
	"\apayment\x18\x01 \x01(\v2\x14.api.payment.PaymentR\apayment\"2\n" +
	"\x11GetPaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\"D\n" +
	"\x12GetPaymentResponse\x12.\n" +
	"\apayment\x18\x01 \x01(\v2\x14.api.payment.PaymentR\apayment\"=\n" +
	"\x1cListPaymentsByAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"Q\n" +
	"\x1dListPaymentsByAccountResponse\x120\n" +
	"\bpayments\x18\x01 \x03(\v2\x14.api.payment.PaymentR\bpayments\"S\n" +
	"\x1aUpdatePaymentStatusRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\x88\x04\n" +
	"\x0ePaymentService\x12r\n" +
	"\rCreatePayment\x12!.api.payment.CreatePaymentRequest\x1a\".api.payment.CreatePaymentResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/payment/create\x12l\n" +
	"\n" +
	"GetPayment\x12\x1e.api.payment.GetPaymentRequest\x1a\x1f.api.payment.GetPaymentResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/payment/{payment_id}\x12\x95\x01\n" +
	"\x15ListPaymentsByAccount\x12).api.payment.ListPaymentsByAccountRequest\x1a*.api.payment.ListPaymentsByAccountResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/account/{account_id}/payment\x12|\n" +
	"\x13UpdatePaymentStatus\x12'.api.payment.UpdatePaymentStatusRequest\x1a\x14.api.payment.Payment\"&\x82\xd3\xe4\x93\x02 :\x01*2\x1b/payment/{payment_id}/statuB4\n" +
	"\vapi.paymentP\x01Z#payment-service/api/payment;paymentb\x06proto3"

var (
	file_api_payment_payment_proto_rawDescOnce sync.Once
	file_api_payment_payment_proto_rawDescData []byte
)

func file_api_payment_payment_proto_rawDescGZIP() []byte {
	file_api_payment_payment_proto_rawDescOnce.Do(func() {
		file_api_payment_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_payment_payment_proto_rawDesc), len(file_api_payment_payment_proto_rawDesc)))
	})
	return file_api_payment_payment_proto_rawDescData
}

var file_api_payment_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_payment_payment_proto_goTypes = []any{
	(*Payment)(nil),                       // 0: api.payment.Payment
	(*CreatePaymentRequest)(nil),          // 1: api.payment.CreatePaymentRequest
	(*CreatePaymentResponse)(nil),         // 2: api.payment.CreatePaymentResponse
	(*GetPaymentRequest)(nil),             // 3: api.payment.GetPaymentRequest
	(*GetPaymentResponse)(nil),            // 4: api.payment.GetPaymentResponse
	(*ListPaymentsByAccountRequest)(nil),  // 5: api.payment.ListPaymentsByAccountRequest
	(*ListPaymentsByAccountResponse)(nil), // 6: api.payment.ListPaymentsByAccountResponse
	(*UpdatePaymentStatusRequest)(nil),    // 7: api.payment.UpdatePaymentStatusRequest
	(*timestamppb.Timestamp)(nil),         // 8: google.protobuf.Timestamp
}
var file_api_payment_payment_proto_depIdxs = []int32{
	8,  // 0: api.payment.Payment.scheduled_at:type_name -> google.protobuf.Timestamp
	8,  // 1: api.payment.Payment.processed_at:type_name -> google.protobuf.Timestamp
	8,  // 2: api.payment.Payment.creation_time:type_name -> google.protobuf.Timestamp
	8,  // 3: api.payment.Payment.modified_time:type_name -> google.protobuf.Timestamp
	8,  // 4: api.payment.CreatePaymentRequest.scheduled_at:type_name -> google.protobuf.Timestamp
	0,  // 5: api.payment.CreatePaymentResponse.payment:type_name -> api.payment.Payment
	0,  // 6: api.payment.GetPaymentResponse.payment:type_name -> api.payment.Payment
	0,  // 7: api.payment.ListPaymentsByAccountResponse.payments:type_name -> api.payment.Payment
	1,  // 8: api.payment.PaymentService.CreatePayment:input_type -> api.payment.CreatePaymentRequest
	3,  // 9: api.payment.PaymentService.GetPayment:input_type -> api.payment.GetPaymentRequest
	5,  // 10: api.payment.PaymentService.ListPaymentsByAccount:input_type -> api.payment.ListPaymentsByAccountRequest
	7,  // 11: api.payment.PaymentService.UpdatePaymentStatus:input_type -> api.payment.UpdatePaymentStatusRequest
	2,  // 12: api.payment.PaymentService.CreatePayment:output_type -> api.payment.CreatePaymentResponse
	4,  // 13: api.payment.PaymentService.GetPayment:output_type -> api.payment.GetPaymentResponse
	6,  // 14: api.payment.PaymentService.ListPaymentsByAccount:output_type -> api.payment.ListPaymentsByAccountResponse
	0,  // 15: api.payment.PaymentService.UpdatePaymentStatus:output_type -> api.payment.Payment
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_payment_payment_proto_init() }
func file_api_payment_payment_proto_init() {
	if File_api_payment_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_payment_payment_proto_rawDesc), len(file_api_payment_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_payment_payment_proto_goTypes,
		DependencyIndexes: file_api_payment_payment_proto_depIdxs,
		MessageInfos:      file_api_payment_payment_proto_msgTypes,
	}.Build()
	File_api_payment_payment_proto = out.File
	file_api_payment_payment_proto_goTypes = nil
	file_api_payment_payment_proto_depIdxs = nil
}
