// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.2
// source: api/payment/payment.proto

package payment

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationPaymentServiceCreatePayment = "/api.payment.PaymentService/CreatePayment"
const OperationPaymentServiceGetPayment = "/api.payment.PaymentService/GetPayment"
const OperationPaymentServiceListPaymentsByAccount = "/api.payment.PaymentService/ListPaymentsByAccount"
const OperationPaymentServiceUpdatePaymentStatus = "/api.payment.PaymentService/UpdatePaymentStatus"

type PaymentServiceHTTPServer interface {
	CreatePayment(context.Context, *CreatePaymentRequest) (*CreatePaymentResponse, error)
	GetPayment(context.Context, *GetPaymentRequest) (*GetPaymentResponse, error)
	ListPaymentsByAccount(context.Context, *ListPaymentsByAccountRequest) (*ListPaymentsByAccountResponse, error)
	UpdatePaymentStatus(context.Context, *UpdatePaymentStatusRequest) (*Payment, error)
}

func RegisterPaymentServiceHTTPServer(s *http.Server, srv PaymentServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/payment/create", _PaymentService_CreatePayment0_HTTP_Handler(srv))
	r.GET("/payment/{payment_id}", _PaymentService_GetPayment0_HTTP_Handler(srv))
	r.GET("/account/{account_id}/payment", _PaymentService_ListPaymentsByAccount0_HTTP_Handler(srv))
	r.PATCH("/payment/{payment_id}/statu", _PaymentService_UpdatePaymentStatus0_HTTP_Handler(srv))
}

func _PaymentService_CreatePayment0_HTTP_Handler(srv PaymentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreatePaymentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPaymentServiceCreatePayment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreatePayment(ctx, req.(*CreatePaymentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreatePaymentResponse)
		return ctx.Result(200, reply)
	}
}

func _PaymentService_GetPayment0_HTTP_Handler(srv PaymentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetPaymentRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPaymentServiceGetPayment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetPayment(ctx, req.(*GetPaymentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetPaymentResponse)
		return ctx.Result(200, reply)
	}
}

func _PaymentService_ListPaymentsByAccount0_HTTP_Handler(srv PaymentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListPaymentsByAccountRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPaymentServiceListPaymentsByAccount)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListPaymentsByAccount(ctx, req.(*ListPaymentsByAccountRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListPaymentsByAccountResponse)
		return ctx.Result(200, reply)
	}
}

func _PaymentService_UpdatePaymentStatus0_HTTP_Handler(srv PaymentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdatePaymentStatusRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPaymentServiceUpdatePaymentStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdatePaymentStatus(ctx, req.(*UpdatePaymentStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Payment)
		return ctx.Result(200, reply)
	}
}

type PaymentServiceHTTPClient interface {
	CreatePayment(ctx context.Context, req *CreatePaymentRequest, opts ...http.CallOption) (rsp *CreatePaymentResponse, err error)
	GetPayment(ctx context.Context, req *GetPaymentRequest, opts ...http.CallOption) (rsp *GetPaymentResponse, err error)
	ListPaymentsByAccount(ctx context.Context, req *ListPaymentsByAccountRequest, opts ...http.CallOption) (rsp *ListPaymentsByAccountResponse, err error)
	UpdatePaymentStatus(ctx context.Context, req *UpdatePaymentStatusRequest, opts ...http.CallOption) (rsp *Payment, err error)
}

type PaymentServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewPaymentServiceHTTPClient(client *http.Client) PaymentServiceHTTPClient {
	return &PaymentServiceHTTPClientImpl{client}
}

func (c *PaymentServiceHTTPClientImpl) CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...http.CallOption) (*CreatePaymentResponse, error) {
	var out CreatePaymentResponse
	pattern := "/payment/create"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPaymentServiceCreatePayment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PaymentServiceHTTPClientImpl) GetPayment(ctx context.Context, in *GetPaymentRequest, opts ...http.CallOption) (*GetPaymentResponse, error) {
	var out GetPaymentResponse
	pattern := "/payment/{payment_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPaymentServiceGetPayment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PaymentServiceHTTPClientImpl) ListPaymentsByAccount(ctx context.Context, in *ListPaymentsByAccountRequest, opts ...http.CallOption) (*ListPaymentsByAccountResponse, error) {
	var out ListPaymentsByAccountResponse
	pattern := "/account/{account_id}/payment"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPaymentServiceListPaymentsByAccount))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PaymentServiceHTTPClientImpl) UpdatePaymentStatus(ctx context.Context, in *UpdatePaymentStatusRequest, opts ...http.CallOption) (*Payment, error) {
	var out Payment
	pattern := "/payment/{payment_id}/statu"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPaymentServiceUpdatePaymentStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
