// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/balance/balance.proto

package balance

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Balance struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccountId        string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AvailableBalance string                 `protobuf:"bytes,2,opt,name=available_balance,json=availableBalance,proto3" json:"available_balance,omitempty"`
	PendingBalance   string                 `protobuf:"bytes,3,opt,name=pending_balance,json=pendingBalance,proto3" json:"pending_balance,omitempty"`
	Currency         string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	ChangeAmount     string                 `protobuf:"bytes,5,opt,name=change_amount,json=changeAmount,proto3" json:"change_amount,omitempty"`
	ChangeReason     string                 `protobuf:"bytes,6,opt,name=change_reason,json=changeReason,proto3" json:"change_reason,omitempty"`
	BalanceTimestamp *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=balance_timestamp,json=balanceTimestamp,proto3" json:"balance_timestamp,omitempty"`
	BalanceDate      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=balance_date,json=balanceDate,proto3" json:"balance_date,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Balance) Reset() {
	*x = Balance{}
	mi := &file_api_balance_balance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Balance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Balance) ProtoMessage() {}

func (x *Balance) ProtoReflect() protoreflect.Message {
	mi := &file_api_balance_balance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Balance.ProtoReflect.Descriptor instead.
func (*Balance) Descriptor() ([]byte, []int) {
	return file_api_balance_balance_proto_rawDescGZIP(), []int{0}
}

func (x *Balance) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Balance) GetAvailableBalance() string {
	if x != nil {
		return x.AvailableBalance
	}
	return ""
}

func (x *Balance) GetPendingBalance() string {
	if x != nil {
		return x.PendingBalance
	}
	return ""
}

func (x *Balance) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Balance) GetChangeAmount() string {
	if x != nil {
		return x.ChangeAmount
	}
	return ""
}

func (x *Balance) GetChangeReason() string {
	if x != nil {
		return x.ChangeReason
	}
	return ""
}

func (x *Balance) GetBalanceTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.BalanceTimestamp
	}
	return nil
}

func (x *Balance) GetBalanceDate() *timestamppb.Timestamp {
	if x != nil {
		return x.BalanceDate
	}
	return nil
}

type RecordBalanceChangeRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccountId        string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AvailableBalance string                 `protobuf:"bytes,2,opt,name=available_balance,json=availableBalance,proto3" json:"available_balance,omitempty"`
	PendingBalance   string                 `protobuf:"bytes,3,opt,name=pending_balance,json=pendingBalance,proto3" json:"pending_balance,omitempty"`
	Currency         string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	ChangeAmount     string                 `protobuf:"bytes,5,opt,name=change_amount,json=changeAmount,proto3" json:"change_amount,omitempty"`
	ChangeReason     string                 `protobuf:"bytes,6,opt,name=change_reason,json=changeReason,proto3" json:"change_reason,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RecordBalanceChangeRequest) Reset() {
	*x = RecordBalanceChangeRequest{}
	mi := &file_api_balance_balance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordBalanceChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordBalanceChangeRequest) ProtoMessage() {}

func (x *RecordBalanceChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_balance_balance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordBalanceChangeRequest.ProtoReflect.Descriptor instead.
func (*RecordBalanceChangeRequest) Descriptor() ([]byte, []int) {
	return file_api_balance_balance_proto_rawDescGZIP(), []int{1}
}

func (x *RecordBalanceChangeRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *RecordBalanceChangeRequest) GetAvailableBalance() string {
	if x != nil {
		return x.AvailableBalance
	}
	return ""
}

func (x *RecordBalanceChangeRequest) GetPendingBalance() string {
	if x != nil {
		return x.PendingBalance
	}
	return ""
}

func (x *RecordBalanceChangeRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *RecordBalanceChangeRequest) GetChangeAmount() string {
	if x != nil {
		return x.ChangeAmount
	}
	return ""
}

func (x *RecordBalanceChangeRequest) GetChangeReason() string {
	if x != nil {
		return x.ChangeReason
	}
	return ""
}

type GetCurrentBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentBalanceRequest) Reset() {
	*x = GetCurrentBalanceRequest{}
	mi := &file_api_balance_balance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentBalanceRequest) ProtoMessage() {}

func (x *GetCurrentBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_balance_balance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentBalanceRequest) Descriptor() ([]byte, []int) {
	return file_api_balance_balance_proto_rawDescGZIP(), []int{2}
}

func (x *GetCurrentBalanceRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetBalanceHistoryRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	AccountId string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// Optional filters
	FromDate      string `protobuf:"bytes,2,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"` //YYYY-MM-DD
	ToDate        string `protobuf:"bytes,3,opt,name=to_date,json=toDate,proto3" json:"to_date,omitempty"`       //YYYY-MM-DD
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceHistoryRequest) Reset() {
	*x = GetBalanceHistoryRequest{}
	mi := &file_api_balance_balance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceHistoryRequest) ProtoMessage() {}

func (x *GetBalanceHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_balance_balance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceHistoryRequest) Descriptor() ([]byte, []int) {
	return file_api_balance_balance_proto_rawDescGZIP(), []int{3}
}

func (x *GetBalanceHistoryRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetBalanceHistoryRequest) GetFromDate() string {
	if x != nil {
		return x.FromDate
	}
	return ""
}

func (x *GetBalanceHistoryRequest) GetToDate() string {
	if x != nil {
		return x.ToDate
	}
	return ""
}

type GetBalanceHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balances      []*Balance             `protobuf:"bytes,1,rep,name=balances,proto3" json:"balances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceHistoryResponse) Reset() {
	*x = GetBalanceHistoryResponse{}
	mi := &file_api_balance_balance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceHistoryResponse) ProtoMessage() {}

func (x *GetBalanceHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_balance_balance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceHistoryResponse) Descriptor() ([]byte, []int) {
	return file_api_balance_balance_proto_rawDescGZIP(), []int{4}
}

func (x *GetBalanceHistoryResponse) GetBalances() []*Balance {
	if x != nil {
		return x.Balances
	}
	return nil
}

var File_api_balance_balance_proto protoreflect.FileDescriptor

const file_api_balance_balance_proto_rawDesc = "" +
	"\n" +
	"\x19api/balance/balance.proto\x12\vapi.balance\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xec\x02\n" +
	"\aBalance\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12+\n" +
	"\x11available_balance\x18\x02 \x01(\tR\x10availableBalance\x12'\n" +
	"\x0fpending_balance\x18\x03 \x01(\tR\x0ependingBalance\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12#\n" +
	"\rchange_amount\x18\x05 \x01(\tR\fchangeAmount\x12#\n" +
	"\rchange_reason\x18\x06 \x01(\tR\fchangeReason\x12G\n" +
	"\x11balance_timestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x10balanceTimestamp\x12=\n" +
	"\fbalance_date\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vbalanceDate\"\xf7\x01\n" +
	"\x1aRecordBalanceChangeRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12+\n" +
	"\x11available_balance\x18\x02 \x01(\tR\x10availableBalance\x12'\n" +
	"\x0fpending_balance\x18\x03 \x01(\tR\x0ependingBalance\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12#\n" +
	"\rchange_amount\x18\x05 \x01(\tR\fchangeAmount\x12#\n" +
	"\rchange_reason\x18\x06 \x01(\tR\fchangeReason\"9\n" +
	"\x18GetCurrentBalanceRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"o\n" +
	"\x18GetBalanceHistoryRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1b\n" +
	"\tfrom_date\x18\x02 \x01(\tR\bfromDate\x12\x17\n" +
	"\ato_date\x18\x03 \x01(\tR\x06toDate\"M\n" +
	"\x19GetBalanceHistoryResponse\x120\n" +
	"\bbalances\x18\x01 \x03(\v2\x14.api.balance.BalanceR\bbalances2\x88\x03\n" +
	"\x0eBalanceService\x12i\n" +
	"\x13RecordBalanceChange\x12'.api.balance.RecordBalanceChangeRequest\x1a\x14.api.balance.Balance\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/balance\x12w\n" +
	"\x11GetCurrentBalance\x12%.api.balance.GetCurrentBalanceRequest\x1a\x14.api.balance.Balance\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/account/{account_id}/balance\x12\x91\x01\n" +
	"\x11GetBalanceHistory\x12%.api.balance.GetBalanceHistoryRequest\x1a&.api.balance.GetBalanceHistoryResponse\"-\x82\xd3\xe4\x93\x02'\x12%/account/{account_id}/balance/historyB4\n" +
	"\vapi.balanceP\x01Z#balance-service/api/balance;balanceb\x06proto3"

var (
	file_api_balance_balance_proto_rawDescOnce sync.Once
	file_api_balance_balance_proto_rawDescData []byte
)

func file_api_balance_balance_proto_rawDescGZIP() []byte {
	file_api_balance_balance_proto_rawDescOnce.Do(func() {
		file_api_balance_balance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_balance_balance_proto_rawDesc), len(file_api_balance_balance_proto_rawDesc)))
	})
	return file_api_balance_balance_proto_rawDescData
}

var file_api_balance_balance_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_balance_balance_proto_goTypes = []any{
	(*Balance)(nil),                    // 0: api.balance.Balance
	(*RecordBalanceChangeRequest)(nil), // 1: api.balance.RecordBalanceChangeRequest
	(*GetCurrentBalanceRequest)(nil),   // 2: api.balance.GetCurrentBalanceRequest
	(*GetBalanceHistoryRequest)(nil),   // 3: api.balance.GetBalanceHistoryRequest
	(*GetBalanceHistoryResponse)(nil),  // 4: api.balance.GetBalanceHistoryResponse
	(*timestamppb.Timestamp)(nil),      // 5: google.protobuf.Timestamp
}
var file_api_balance_balance_proto_depIdxs = []int32{
	5, // 0: api.balance.Balance.balance_timestamp:type_name -> google.protobuf.Timestamp
	5, // 1: api.balance.Balance.balance_date:type_name -> google.protobuf.Timestamp
	0, // 2: api.balance.GetBalanceHistoryResponse.balances:type_name -> api.balance.Balance
	1, // 3: api.balance.BalanceService.RecordBalanceChange:input_type -> api.balance.RecordBalanceChangeRequest
	2, // 4: api.balance.BalanceService.GetCurrentBalance:input_type -> api.balance.GetCurrentBalanceRequest
	3, // 5: api.balance.BalanceService.GetBalanceHistory:input_type -> api.balance.GetBalanceHistoryRequest
	0, // 6: api.balance.BalanceService.RecordBalanceChange:output_type -> api.balance.Balance
	0, // 7: api.balance.BalanceService.GetCurrentBalance:output_type -> api.balance.Balance
	4, // 8: api.balance.BalanceService.GetBalanceHistory:output_type -> api.balance.GetBalanceHistoryResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_balance_balance_proto_init() }
func file_api_balance_balance_proto_init() {
	if File_api_balance_balance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_balance_balance_proto_rawDesc), len(file_api_balance_balance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_balance_balance_proto_goTypes,
		DependencyIndexes: file_api_balance_balance_proto_depIdxs,
		MessageInfos:      file_api_balance_balance_proto_msgTypes,
	}.Build()
	File_api_balance_balance_proto = out.File
	file_api_balance_balance_proto_goTypes = nil
	file_api_balance_balance_proto_depIdxs = nil
}
