// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"customer-service/internal/conf"
	"customer-service/internal/data"
	"customer-service/internal/handler"
	"customer-service/internal/server"
	"customer-service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	customerRepo := data.NewCustomerRepo(dataData, logger)
	customerUseCase := handler.NewCustomerUseCase(customerRepo)
	customerServiceService := service.NewCustomerServiceService(customerUseCase)
	grpcServer := server.NewGRPCServer(confServer, customerServiceService, logger)
	httpServer := server.NewHTTPServer(confServer, customerServiceService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
