// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"account-service/internal/client"
	"account-service/internal/conf"
	"account-service/internal/data"
	"account-service/internal/handler"
	"account-service/internal/server"
	"account-service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	accountRepo := data.NewAccountRepo(dataData)
	customerServiceClient := client.NewCustomerServiceClient()
	customerClient := client.NewCustomerClient(customerServiceClient)
	accountUsecase := handler.NewAccountUsecase(accountRepo, customerClient)
	accountServiceService := service.NewAccountServiceService(accountUsecase)
	grpcServer := server.NewGRPCServer(confServer, accountServiceService, logger)
	httpServer := server.NewHTTPServer(confServer, accountServiceService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
